DEPENDENCIES: {}

TOKENS:
  PRODUCTION: null
  DEVELOPMENT: null

GUILD_IDS:
  DEV: null
  MAIN: null

DEVELOPERS: []

APPLICATION_IDS:
  PRODUCTION: null
  DEVELOPMENT: null

TOURNAMENT:
  TRIGGER_CHANNELS: [{ "ID": 123, "TYPE": 2 }, { "ID": 456, "TYPE": 3 }]

NAME_ROLES: { 123: "SSL", 456: "GC3" }
LEGACY_ROLES: [123, 456]

SIX_MAN:
  CATEGORY: 123456
