DEPENDENCIES: {}

TOKENS:
  PRODUCTION: null
  DEVELOPMENT: null

GUILD_IDS:
  DEV: null
  MAIN: null

DEVELOPERS: [] # Intending to be removed

APPLICATION_IDS: # Intending to be removed
  PRODUCTION: null
  DEVELOPMENT: null

TOURNAMENT: 
    TRIGGER_CHANNELS: [
    {"ID": 123456789, "TYPE": 2},
    {"ID": 234567891, "TYPE": 3}
]

NAME_ROLES: { 1234: "RANK 1", 5678: "RANK 2" }

LOGGING:  {
    "version": 1,
    "formatters": {
        "standard": {
            "format": "%(asctime)s %(levelname)-6s %(name)-15s %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S"
        },
        "ColouredFormatter": {
            "()": "utils.ColouredFormatter.ColouredFormatter"
        }
    },
    "handlers": {
        "file": {
            "class": "logging.handlers.RotatingFileHandler",
            "formatter": "standard",
            "level": "DEBUG",
            "filename": "logs/latest.log",
            "mode": "w",
            'maxBytes': 100000,
            'backupCount': 5,
        },
        "stdout": {
            "class": "logging.StreamHandler",
            "formatter": "ColouredFormatter",
            "level": "INFO",
            "stream": "ext://sys.stdout"
        }
    },
    "loggers": {
        "": {
            "level": "DEBUG",
            "handlers": [
                "file", "stdout"
            ],
            "propagate": False
        }
    }
}
